### PR TITLE
Add optional PROXY_IP variable to set ORB proxy

### PR DESCRIPTION
**Pull request by gytis**

### CODE REVIEW

**Comment by gytis** [comment]
Could somebody review this please?

**Comment by goldmann** [comment]
Merged.

**Comment by gytis** [comment]
thanks, @goldmann . Would be great, if you could trigger the build on Docker Hub too. Thanks!

**Comment by goldmann** [comment]
Done.

**Comment by gytis** [comment]
Thanks, Marek!

**Pull request merged**
