### PR TITLE
Fixed jacorb name server ip grep

### PR DESCRIPTION
**Pull request by gytis**

### CODE REVIEW

**Comment by gytis** [comment]
@goldmann , could somebody merge this in please?

**Comment by goldmann** [comment]
I wonder if there is a more clean way to do it, but, merging...

**Comment by gytis** [comment]
Is there a recommended way of extracting host ip?

**Comment by goldmann** [comment]
You could use: `hostname -i`, for example.

**Comment by goldmann** [comment]
But I wouldn't say it's recommended way, but it is a simple one, that should work in your case.

**Comment by gytis** [comment]
Yeah it's definitely nicer for the host IP.
But if I remember correctly, to get linked container's IP (i.e. jacrob) I
should still use /etc/hosts rather than environment variable, right?

**Comment by goldmann** [comment]
The term "host ip" is a bit ambiguous (Docekr host IP, container IP from inside of the container, etc), let's try to describe it in a different way :)

If you link containers together you should use the env variable created by docker to get the IP address of the linked container.

**Comment by gytis** [comment]
True, I meant container IP :)

As for the linked container IP, I was referring to "Important notes on
Docker environment variables" part of
https://docs.docker.com/userguide/dockerlinks/. Where they recommend using
/etc/hosts rather than environment variables.

**Comment by goldmann** [comment]
I'm a bit unsure which version added this feature, but in this case just use the name of the container, this will be resolved properly and you will not need to touch the hosts file at all. So, in your case instead of setting `JACORB_NAME_SERVER_IP` just make sure you use `jacorb-name-server` as the value. This should be resolved to the correct IP.

**Comment by gytis** [comment]
Hmm, doesn't seem to work for me on Docker 1.8.1. I guess I'll just leave
it as it is for now.

**Comment by goldmann** [comment]
Well, Jacorb needs to support it. If it expects IP address, then IP address should be provided instead of the name.

**Pull request merged**
